### ISSUE TITLE
ArrayIndexOutOfBoundsException when using RopeJoints

### ISSUE THREAD

**Issue by fschoellhammer** [jbox2d/jbox2d#39]
Hi,

I have already been working quite a bit with JBox2d (2.2.1.1) in my Android app and all was working fine so far (thanks for this great library!)

However, when I started to use *RopeJoint* in my app, it starts to crash. 
 
    java.lang.ArrayIndexOutOfBoundsException: length=100; index=100
            at org.jbox2d.pooling.normal.OrderedStack.pop(OrderedStack.java:52)
            at org.jbox2d.pooling.normal.DefaultWorldPool.popRot(DefaultWorldPool.java:226)
            at org.jbox2d.dynamics.joints.RopeJoint.solvePositionConstraints(RopeJoint.java:194)
            at org.jbox2d.dynamics.Island.solve(Island.java:371)
            at org.jbox2d.dynamics.World.solve(World.java:1085)
            at org.jbox2d.dynamics.World.step(World.java:598)

It does not occur all the time, but often enough to easily reproduce it and I am have no clue what I can do about it.

I am running JBox2D on Android (5.1.1), all operations are executed on a single thread:

My programm only has 2 bodies (static + dynamic) and one joint. Before each step I apply a force to the body. After a few rounds of iterations (like 20-30) my app crashes (not always, but well reproduceable)

world = new World(new Vec2(0.0f, 0.0f));

    // create dynamic object

    final BodyDef bd = new BodyDef();
    bd.type = BodyType.DYNAMIC;

    CircleShape cs = new CircleShape();
    cs.m_radius = radiusWorld;

    FixtureDef fd = new FixtureDef();
    fd.shape = cs;
    fd.density = 0.2f;
    fd.friction = 0.0f;
    fd.restitution = 1.0f;

    Body dynBody = world.createBody(bd);
    dynBody.setLinearDamping(0.01f);
    dynBody.createFixture(fd);

    // create static body

    BodyDef bd = new BodyDef();
    bd.type = BodyType.STATIC;
    Body staticBody = world.createBody(bd);

    // create joint

    RopeJointDef joint = new RopeJointDef();
    joint.bodyA = staticBody;
    joint.bodyB = dynBody;
    joint.collideConnected = false;
    joint.maxLength = ropeLength;
    joint.localAnchorA.set(staticBody.getLocalCenter());
    joint.localAnchorB.set(dynBody.getLocalCenter());
    world.createJoint(joint);

    ...

    // calculate

    dynBody.applyForceToCenter(...)
    world.step(dt, 6, 3)

Can this be caused by a programming error? If yes, any tips what I might be doing wrong? Or can this possibly be a problem in the library. If yes, any fixes/workarounds or how I can debug this for certain.

I would really appreciate if someone can help me out here.

Thanks,
Flo

**Comment by fschoellhammer** [comment]
I read the Box2D manual again, which states:

http://box2d.org/manual.pdf
"Do not create a body at the origin and then move it. If you create several bodies at
the origin, then performance will suffer."

After creating my bodies on a different position than origin the problem seems to disappear.
